package de.app.fivegla.fiware.api;

import lombok.extern.slf4j.Slf4j;

import java.util.UUID;

/**
 * This class provides methods for generating FIWARE IDs.
 * FIWARE IDs are used to uniquely identify entities in the FIWARE ecosystem.
 */
@Slf4j
public class FiwareIdGenerator {

    /**
     * Generates a unique identifier with the given prefix.
     * The generated identifier is a combination of the prefix and two parts of a randomly generated UUID string.
     * If the length of the generated identifier exceeds 62 characters, a FiwareIntegrationLayerException will be thrown.
     *
     * @param prefix the prefix to be appended to the randomly generated UUID parts
     * @return a unique identifier generated by combining the prefix and two parts of a randomly generated UUID string
     * @throws FiwareIntegrationLayerException if the length of the generated identifier exceeds 62 characters
     */
    public static String id(String prefix) {
        var randomUUIDParts = UUID.randomUUID().toString().split("-");
        var fiwareId = prefix + randomUUIDParts[0] + randomUUIDParts[1];
        if (fiwareId.length() > 62) {
            throw new FiwareIntegrationLayerException("The generated id is too long. Please choose a shorter prefix.");
        } else {
            log.debug("Generated id: " + fiwareId);
            return fiwareId;
        }
    }

    /**
     * Generates a unique ID.
     *
     * @return a unique ID string
     */
    public static String id() {
        return id("");
    }

}
