package de.app.fivegla.fiware.api;

import lombok.extern.slf4j.Slf4j;

import java.util.UUID;

/**
 * This class provides methods for generating FIWARE IDs.
 * FIWARE IDs are used to uniquely identify entities in the FIWARE ecosystem.
 */
@Slf4j
public final class FiwareIdGenerator {

    public static final int MAX_ID_LENGTH = 62;

    private FiwareIdGenerator() {
        // private constructor to prevent instantiation
    }

    /**
     * Generates a unique identifier with the given prefix.
     * The generated identifier is a combination of the prefix and two parts of a randomly generated UUID string.
     * If the length of the generated identifier exceeds 62 characters, a FiwareIntegrationLayerException will be thrown.
     *
     * @param prefix the prefix to be appended to the randomly generated UUID parts
     * @return a unique identifier generated by combining the prefix and two parts of a randomly generated UUID string
     * @throws FiwareIntegrationLayerException if the length of the generated identifier exceeds 62 characters
     */
    public static String id(String prefix) {
        var randomUUIDParts = UUID.randomUUID().toString().split("-");
        var fiwareId = prefix + randomUUIDParts[0] + randomUUIDParts[1];
        check(fiwareId);
        log.debug("Generated id: " + fiwareId);
        return fiwareId;
    }

    /**
     * Generates a unique ID.
     *
     * @return a unique ID string
     */
    public static String id() {
        return id("");
    }

    /**
     * Checks if the given ID is valid.
     *
     * @param id the ID to be checked
     * @throws FiwareIntegrationLayerException if the ID is too long
     */
    public static void check(String id) {
        if (id.length() > MAX_ID_LENGTH) {
            log.error("The id is too long. Please choose a shorter prefix.");
            log.debug("Checked ID: " + id);
            throw new FiwareIntegrationLayerException("The generated id is too long. Please choose a shorter prefix.");
        }
    }

}
